# Generated by Django 5.0.4 on 2024-05-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperTrail_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('img', 'Image')], max_length=4),
        ),
    ]
