# Generated by Django 5.0.4 on 2024-05-12 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperTrail_App', '0002_alter_document_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotaions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_value', models.CharField(max_length=500)),
                ('target_selector_value', models.CharField(max_length=255)),
                ('page_number', models.IntegerField(default=1)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='PaperTrail_App.document')),
            ],
            options={
                'verbose_name': 'Image Annotaion',
                'verbose_name_plural': 'Image Annotaions',
            },
        ),
        migrations.DeleteModel(
            name='ImageAnnotaion',
        ),
    ]
