# Generated by Django 5.0.4 on 2024-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperTrail_App', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
