# Generated by Django 5.0.4 on 2024-05-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaperTrail_App', '0003_annotaions_delete_imageannotaion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotaions',
            options={'verbose_name': 'Annotaion', 'verbose_name_plural': 'Annotaions'},
        ),
    ]
