# Generated by Django 5.0.4 on 2024-05-12 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperTrail_App', '0004_alter_annotaions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
