# Generated by Django 5.0.4 on 2024-04-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperTrail_App', '0004_alter_document_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
